#!/bin/bash
set -e
tmp="tmp.$RANDOM.js"
out="webtask.pack.js"
tsc
echo '"use strict";' >> "$tmp"
cat dist/parser.js >> "$tmp"
cat dist/theme.js >> "$tmp"
cat dist/core.js >> "$tmp"
cat dist/main.js >> "$tmp"
cat dist/webtask.js >> "$tmp"
cat "$tmp" \
  | grep -v 'import.*"\./.*"' \
  | sed 's/^export //' \
  > "$out"
rm "$tmp"
cat "$out" | xclip -sel clipboard
